### PR TITLE
Added more vim-ish movement

### LINKED ISSUE #31: Invert some of the mapping
- C-H should 'move the split' to the left, and C-L to the right.
- C-J should do CCW and not CW. C-K should do C-W 

This makes more sense in how the keys are mapped, that might differ from DWM as a philosophy tho.

The project looks stellar now, nice done!

### PR DESCRIPTION
**Pull request by teoljungberg**
This makes more sense, atleast in my optinion, considering it's vim we are talking about. And the use of the homerow

Resolves #31

### CODE REVIEW

**Comment by spolu** [comment]
Again, `J` should let you go down your stacked buffers. So I think  it should not be inverted. Ok for `H` and `L`

**Comment by teoljungberg** [comment]
What I changed is just the mappings, so:
- C-J moves CCW
- C-K moves CW
- C-H resized to the left
- C-L resized to the right

**Comment by spolu** [comment]
I understand and I disagree with the C-J / C-K inversion.

**Comment by teoljungberg** [comment]
Do you want me to change the commits to just handle resizing?

**Comment by spolu** [comment]
That'd be awesome! + pull master so that it is directly mergeable from here :)

**Comment by spolu** [comment]
As it is to day w moves CW and W CCW and CW means right then down the stack of buffers.

**Comment by teoljungberg** [comment]
IMHO, I don't the the issues with my remapping. But thats not an issue, changing

**Comment by teoljungberg** [comment]
> That'd be awesome! + pull master so that it is directly mergeable from here :)

Or do you want me to create another PR, from my master to your master? That's not necessary, the PR is from my branch vim-movement to your master

**Comment by spolu** [comment]
Thanks!

**Pull request merged**
