### PR TITLE
Add <Plug> maps

### PR DESCRIPTION
**Pull request by tpope**
These are convenient hooks for those that wish to provide their own mappings.

### CODE REVIEW

**Comment by spolu** [comment]
I'm no expert in key binding in vim. What's the purpose of nnoremap compared to a nmap with <Plug>?

**Comment by lmarburger** [comment]
@tpope mentioned over on #30 (which is where I learned the difference):

> Note the `nore` portion means "don't invoke maps recursively", which guards against the unlikely case that someone has remapped colon.

**Comment by spolu** [comment]
Shouldn't it be preserved here?

**Comment by tpope** [comment]
You mean in the second set of maps? They invoke other maps recursively, so they have to be `map`s, not `noremap`s.

**Comment by spolu** [comment]
make sense

**Pull request merged**
