### PR TITLE
Auto updates layout when a new buffer is opened

### PR DESCRIPTION
**Pull request by fjolnir**
This was driving me nuts.

### CODE REVIEW

**Comment by spolu** [comment]
No need for a `DWM_Update()` function. See the new `DWM_Focus()` function (https://github.com/spolu/dwm.vim/pull/16)

I like this feature but I find it quite agressive.
Can you protect this by an option deactivated by default. (you'll the be able to set it in your .vimrc)

Thanks!

**Comment by lmarburger** [comment]
I'm testing this feature for #19. Using `BufNewFile` and `BufRead` work when reading in a file with `:edit` but doesn't catch `:new`, or `:split`. Do you happen to know what would catch those as well? It also fires on `:help`. Is that expected?

**Comment by spolu** [comment]
Okay we need to get that in I think

**Comment by spolu** [comment]
This one should go in. @lmarburger do you have something similar for your new implementation?

**Comment by lmarburger** [comment]
Nope. I played around with this and `BufNewFile,BufRead` didn't feel right to me. It'd be nice if it could catch `:split`, `:new` et al. Then people could use their existing split bindings without having to call specific dwm.vim functions.

**Comment by lmarburger** [comment]
I tried this again and it doesn't play nicely with `vim -o one two three four`. It ends up opening a master window for `one` and then three windows for `two`.

**Comment by spolu** [comment]
OK. Catch the new file would be nice no?

**Comment by friggeri** [comment]
FYI I've been looking into this too but haven't been able to come up with anything that does not feel buggy.

**Comment by lmarburger** [comment]
I've changed my mind to disagree with adding this behavior. Most times I don't want to think about how my splits are arranged but there are times when I want to be deliberate about it. If dwm.vim had its hooks into `BufRead` or the like, it would be frustrating for the few times when I want to split the screen in a specific way.

I think I'd be happier to create some custom mappings that I use all the time but still afford the flexibility to `:split` or `:vsplit` if the need arises.

**Comment by spolu** [comment]
What do you think of removing the <C-C> and hooking buffer close on buffer tagged with dwm ?

**Comment by lmarburger** [comment]
I'm not sure if that really appeals to me personally. If I have a mapping to open and close windows using dwm.vim, that frees the option to use the commands manually without dwm.vim interfering.

I can't speculate about what other people would find valuable or what the default should be. I'd prefer to make my own open/close window and focus mappings ignoring all the rest.

**Comment by spolu** [comment]
Well the closing behaviour would only interfere on dwm.vim taggued windows

**Comment by lmarburger** [comment]
Correct. Because I open a window using a dwm.vim binding, that doesn't mean that I definitely want to close it with dwm.vim. If I have one mapping to open a new window promoting it to master and another to close a window and layout the other open windows, I don't see when I'd make use of the automatic layout feature.

This is all speculation on a nonexistent feature. I'd definitely give it a try and share my feedback if it lands as a pull request.

**Comment by spolu** [comment]
This is not relevant anymore...

**Pull request closed without merging**
