### PR TITLE
Autocommands for automatic layout updates

### PR DESCRIPTION
**Pull request by n4kz**
Hi,

Tried to improve layout management.

Solved issues (see #37):
- `:new`
- `:help`
- `:q` and similar

Remains:
- `:split` without arguments from master
- `:Ex` netrw has lots of deep magic so I disabled event handling for buffers with `netrw` type

Please, check carefully before merge =)

### CODE REVIEW

**Comment by spolu** [comment]
Hi! I'll test this branch today...

**Comment by spolu** [comment]
Executing `:help` after creating a new window (`C-N`) crashes my version of vim with:

```
Vim: Caught deadly signal SEGV
Segmentation fault (core dumped)
```

Is it similar for you?

If all window have a buffer opened, it works perfectly though.

**Comment by spolu** [comment]
This is quite annoying as `help` is easy to open mistakingly while working... we wouldn't want to cause vim crashes...

**Comment by spolu** [comment]
Why not call DWM_Focus() ?

**Comment by n4kz** [comment]
Hmm, `<C-N>` + `:help` works as expected. 

```
~ > vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 23 2012 13:50:52)
Compiled by root@apple.com
```

Will try on my linux box soon.

`DWM_AutoEnter()` rebuilds stack completely. I've experimented with `DWM_Focus()` but frequently received three horizontally aligned windows or worse. `DWM_AutoLeave()` requires type-specific logic, to fix `netrw` and probably other magic buffers. 

Also noticed that `:Ex` sometimes hides existing buffer and `:unhide` needed to show it again. Have not found a solution yet :(.

**Comment by n4kz** [comment]
Possible solution

``` viml
if has('autocmd')
  augroup dwm
    au!
    au BufWinEnter * if &l:ft !~ '\v^(netrw|help)$' | call DWM_AutoEnter() | endif
    au BufWinLeave * if &l:ft !~ '\v^(netrw|help)$' | call DWM_AutoLeave() | endif
  augroup end
endif
```

**Comment by spolu** [comment]
Where should it be added?

**Comment by n4kz** [comment]
Replace last lines in [dwm.vim](https://github.com/n4kz/dwm.vim/commit/f0505d471da9820991a72e1dcd96ae0302de782a#diff-071186b6e4b3012a47b3e61abef07f8bR233)

**Comment by spolu** [comment]
Fixes the bug but breaks the layouting when creating new windows (the new window is created at the bottom of the stack)

**Comment by n4kz** [comment]
Mmm, normal window? Can not reproduce, `<C-N>` and `:new` and `:help` are working...

**Comment by spolu** [comment]
Just do 2-3 `<C-N>` ?

**Comment by n4kz** [comment]
Layout is not broken, but new window position depends on active window...

Also `:q` in master window breaks layout...

**Comment by spolu** [comment]
The version on master opens all new window as master which is the expected behaviour.

**Comment by n4kz** [comment]
I see, will try to fix it =)

**Comment by spolu** [comment]
:)

**Comment by n4kz** [comment]
Anything on this? :)

**Comment by spolu** [comment]
Looks good! Still able to generate crashes:

`<F1> <C-C> <F1>`

**Comment by n4kz** [comment]
Okay, reproduced. Thank you =)

**Comment by spolu** [comment]
No prob! Would love to see this PR merged!

**Comment by n4kz** [comment]
Crash fixed, but layout is no longer updated when using `:q` or similar command in empty buffer. However `<C-N><C-C>` works as expected.

**Comment by spolu** [comment]
Nice. Looks good. let me try it for a few hours and I'll merge!

**Comment by spolu** [comment]
Still generating crashes when opening new files...

**Comment by n4kz** [comment]
Can you post here complete command sequence leading to crash?

**Comment by spolu** [comment]
Unfortunately it's transient... but persistently on a `:e`

**Comment by n4kz** [comment]
Looks like autocommands are not the best place for layout changes... I have no crashes but odd behavior and `ml_get` errors from `netrw`. :(

**Comment by spolu** [comment]
Yep... Any other solution in mind?

**Comment by n4kz** [comment]
No, but I'm looking for non-destructive way to update layout.

**Comment by spolu** [comment]
ok!

**Comment by n4kz** [comment]
[Solution](http://stackoverflow.com/questions/6221191/change-cursor-to-another-window-on-bufwritepost-in-vim)

Seems like `feedkeys` works :)

**Comment by n4kz** [comment]
``` viml
silent call feedkeys("\<C-\>\<C-n>\<C-W>K:call DWM_Focus()\<CR>:call DWM_Focus()\<CR>", 'n')
```

Hm...

**Comment by spolu** [comment]
Let me know when you update the PR, so that I can try it out!

**Comment by n4kz** [comment]
Done :)

**Comment by spolu** [comment]
Still experimenting the same crashes :(

**Comment by n4kz** [comment]
Previous commit was better.. `feedkeys` causes noticeable delay in redraw.

Can you tell which autocommand leads to a crash? For example turning them off one by one?

**Comment by spolu** [comment]
Hardly, it's very transient

**Comment by n4kz** [comment]
Removed BufWinLeave. Now we have broken layout on close and no crashes =)

**Comment by n4kz** [comment]
Up :)

**Comment by spolu** [comment]
Hey, I'll try to test it ASAP

**Comment by n4kz** [comment]
Up...

**Comment by n4kz** [comment]
Hi @spolu! Anything new?

**Comment by spolu** [comment]
Hi! Sorry I've been swamped by work. Testing now.

**Comment by spolu** [comment]
Looks good to me!

**Comment by spolu** [comment]
Can you remind me what I should test more precisely?

**Comment by n4kz** [comment]
Hmm.
netrw, help and other special buffers (quickfix, etc.). Looks like all problems were caused by BufWinLeave autocommand.

**Comment by spolu** [comment]
Ok! Absolutely sorry for the delay here.

**Comment by n4kz** [comment]
Happy to see this pull request merged. Thank you =)

**Comment by spolu** [comment]
Well, thank you! :)

**Pull request merged**
