### PR TITLE
Shuffle windows instead of rebuilding

### PR DESCRIPTION
**Pull request by lmarburger**
I love this plugin and I've been thinking a lot about my ideal workflow. I've hacked on a few changes that I would like to see (multiple master windows in #17) and in doing so have stumbled across a few issues due to the approach dwm.vim takes by completely rebuilding windows from all open buffers.
1. The first is I, like @milkmiruku, love my tabs. At present, all open buffers will be shown in all tabs.
2. I'll frequently open a file from another project and `:lcd` to its project directory so I can work from within the project. Every time `DWM_Ball` is called, all windows are destroyed which means the `:lcd` setting is either lost or all new windows will inherit it.

I've been thinking through how I might approach this project of window management in vim. I'm not well versed in vimscript so I would first try the naive approach of using `<C-w>` prefixed mappings. Here's the workflow I recorded. It works in that the outcome is what I expect assuming only 4 open windows.

```
<C-w>H<C-w>w<C-w>J2<C-w>w<C-w>J2<C-w>w<C-w>J<C-w>w<C-w>H
```

Broken down:

Start (bracketed window is active):

```
-------------------------------------
|                 |        S1       |
|                 |-----------------|
|        M        |       [S2]      |
|                 |-----------------|
|                 |        S3       |
-------------------------------------
```

Move S2 left: `<C-w>H`

```
-------------------------------------
|           |           |           |
|           |           |    S1     |
|   [S2]    |     M     |-----------|
|           |           |    S3     |
|           |           |           |
-------------------------------------
```

Move M bottom: `<C-w>w <C-w>J`

```
-------------------------------------
|                 |        S1       |
|       S2        |-----------------|
|                 |        S3       |
|-----------------------------------|
|                [M]                |
-------------------------------------
```

Move S1 down: `2<C-w>w <C-w>J`

```
-------------------------------------
|       S2        |        S3       |
|-----------------------------------|
|                 M                 |
|-----------------------------------|
|               [S1]                |
-------------------------------------
```

Move S3 down: `2<C-w>w <C-w>J`

```
-------------------------------------
|                S2                 |
|-----------------------------------|
|                 M                 |
|-----------------------------------|
|                S1                 |
|-----------------------------------|
|               [S3]                |
-------------------------------------
```

Move S2 left: `<C-w>w <C-w>H`

```
-------------------------------------
|                 |         M       |
|                 |-----------------|
|      [S2]       |        S1       |
|                 |-----------------|
|                 |        S3       |
-------------------------------------
```

I'm sure with some simple vimscript this shuffling window technique could be extended to support any number of open windows.

### CODE REVIEW

**Comment by lmarburger** [comment]
More fun later, it seems `wincmd` is how you mimic `<C-w>` mappings in vimscript. Perhaps more correctly that's the function the built-in mappings call. It has exactly the same result but the benefit is the screen is only redrawn once instead of after each move.

``` vim
function! DWM_Shuffle()
  wincmd H
  if winnr('$') > 2
    for nr in range(2, winnr('$'))
      wincmd w
      wincmd J
      wincmd w
    endfor
  endif
  1wincmd w
  wincmd H
endfunction

map <C-h> :call DWM_Shuffle()<CR>
```

I hope you don't mind my inanity. This was just the gateway into vim that I needed. Learning that a lot of stuff I've been meaning to script is pretty simple.

**Comment by spolu** [comment]
I completely agree with the goal here. If we can find a way to shuffle instead of rebuild so that dwm.vim can become compatible with tables, then I'm all in.
I'm glad the plugin was an incentive to you to dive into VimScript! :)
At the moment it looks like your fix is not completely mature + I'd like to get 
https://github.com/spolu/dwm.vim/pull/9
https://github.com/spolu/dwm.vim/pull/11
in first + mature the key bindings as discussed in #9
Then I'm totally with you to find a better solution for the core handling of windows in dwm.vim!

**Comment by lmarburger** [comment]
@spolu All mappings from #9 are added with the exception of `<C-M>`, `<C-,>` and `<C-.>`. I can the last two once I understand what their purpose. I'm not exactly sure I understand the use case for `DWM_Full`. What if it opened the selected buffer in a new tab?

**Comment by friggeri** [comment]
@spolu @lmarburger Have a look at my [move_around](https://github.com/afriggeri/dwm.vim/tree/move-around) branch, it uses simpler motions than those above, and I've added a layout rotation mechanism.

**Comment by lmarburger** [comment]
Looks good. Can you rebase your branch off spolu/master? That would make it easier to reconcile and focus on this feature without having to pull in #21.

**Comment by lmarburger** [comment]
Scratch that. I think I have it merged correctly.

One change I noticed was changing `<C-j>` and `<C-k>` to rotate the windows instead of simply moving the selection. Is this a legitimate need? I can't see myself using it but maybe others would.

**Comment by lmarburger** [comment]
I removed the rotate feature from this PR. @afriggeri can you send a new PR for it?

**Comment by friggeri** [comment]
@lmarburger My branches are getting totally mixed up right now, on which branch should I rebase mine? Should that be your shuffle-windows branch?

**Comment by lmarburger** [comment]
That would make sense to me. My shuffle-windows branch is connected to this PR. I rebased off your move_around branch at a339f51. The only real change I made was to remove `DWM_Rotate` in 27c234a. If you pull my branch and remove that commit, it should be identical in principle to yours.

**Comment by friggeri** [comment]
I ended up creating a new branch (afriggeri/dwm.vim/shuffle-windows) based on shuffle-windows at 27c234a, could not manage to have a clean history by merging back into move-around (always had two identical commits of my refactor). Not quite sure if I should send the pull request right now or wait until this one is merged though.

**Comment by lmarburger** [comment]
Thanks for merging!

For the record, `<C-M>` hasn't been added to this branch because I didn't understand the use case for it so didn't have a great way to implement it.

**Comment by spolu** [comment]
The idea for <C-M> is to become something close to the mods in xmonad: http://xmonad.org/tour.html

**Pull request merged**
