### PR TITLE
#50: Disable in vimdiff mode

### PR DESCRIPTION
**Pull request by FlashKorten**
Checking for non-diff mode before activating dwm.vim

### CODE REVIEW

**Comment by spolu** [comment]
What about this: https://github.com/spolu/dwm.vim/pull/52 ?

**Comment by rlisowski** [comment]
:+1: works for me

**Comment by rlisowski** [comment]
#52 without #51 not resolving 3-way diff problem

**Comment by rlisowski** [comment]
Thanks a lot.

**Comment by spolu** [comment]
Thanks to you!

**Pull request merged**
