### PR TITLE
Added pane rotation

### PR DESCRIPTION
**Pull request by friggeri**
The rotation should be consistent with the previous/next motions `<c-j>` and `<c-k>`

### CODE REVIEW

**Comment by spolu** [comment]
Looks good !

**Comment by spolu** [comment]
I think these keybindings don't work on OSX

**Comment by friggeri** [comment]
That might be a problem. At first I thought the ideal would be to bind to `Ctrl Shift J` and `Ctrl Shift K` but that's not possible, and I don't really know what other bindings could make sense. Any suggestions ? (personally, I have them mapped to `<Leader>j` and `<Leader>k` myself, and I don't use `<C-J>` or `<C-K>` to move around)

**Comment by spolu** [comment]
Let's keep it that way for now. The functionality is available to the ones who want it. It's just remapping away!

**Pull request merged**
