### PR TITLE
New features: Elegantly handle closed DWM windows, DWM "fix" and "split" functions

### PR DESCRIPTION
**Pull request by jdonaldson**
This combines some of the functions I put together for dwm.vim.

DWM_Fix() will rearrange the windows, essentially stacking them and moving the current window to the main position.

DWM_Split() will perform a reasonable split... E.g., it will create a split directly below itself.  If it's the main window, it will move the split to the stack

There's a new autocommand (enabled by a variable) that will automatically check for "w:dwm" variables when a buffer is closed.  Those variables are set by DWM_New() and DWM_Split().  If the autocommand finds one, it will try to clean up the remaining windows.  It will also adjust the quickfix window so that it always opens along the bottom, since I would imagine most people prefer that.

I tried to avoid making this too opinionated, but let me know if you want things separated out or altered.

### CODE REVIEW

**Comment by spolu** [comment]
Hi Justin, Looks great. I'll test it ASAP. Thanks!

**Comment by spolu** [comment]
This introduces pbs when closing windows that are stacked so this cannot be merged at the moment

**Comment by jdonaldson** [comment]
Yeah, I used this for a while and still had some issues.  Mainly with "info panel" windows that get mixed into the editing buffers during fixes and splits.  What do you mean by pbs though? 

Any ways, keep going with this, dwm is great for smaller screens.  I'm using a wider screen right now, and can comfortably manage triple vertical splits, etc. So I've lost a bit of motivation to make this work.

**Comment by spolu** [comment]
this must be a **BIG** screen! :) I'm using it everyday so, I'll definitely try to make it better! Thanks!

**Pull request closed without merging**
