### PR TITLE
Push master back to stack on C-Space

### PR DESCRIPTION
**Pull request by n4kz**
Now `DWM_Focus` call in master buffer does nothing (except unwanted cursor position change in some cases, probably due to buffer resize). Suggested behaviour - switch back to previously selected buffer if any.

### CODE REVIEW

**Comment by spolu** [comment]
Very nice!

**Comment by n4kz** [comment]
Thank you.

Probably would be better to call `wincmd w` instead of `wincmd p` to select buffer from stack top. Sometimes `wincmd p` is not working, because previous buffer is same as current. I have not investigated this case yet.

**Comment by spolu** [comment]
`wincmd w` seems to work pretty well.

**Comment by spolu** [comment]
If you confirm that it's better, can you make a pull request for that?

**Comment by n4kz** [comment]
Okay. Right after closing current buffer `wincmd p` is not working.

Also noticed that help buffers have slightly different behaviour than normal ones.

**Pull request merged**
