### PR TITLE
Refactor DWM_New()

### PR DESCRIPTION
**Pull request by lmarburger**
It looks like `DWM_New()` can be simplified a little as it duplicates some behavior in `DWM_Focus()`. I came across this while hacking on a way to have more than one vertical split (half-baked PR forthcoming).

### CODE REVIEW

**Comment by spolu** [comment]
nice catch!

**Comment by spolu** [comment]
This was actually erroneous

**Comment by lmarburger** [comment]
I see the fix. What about it wasn't working so I know what to look for?

**Comment by spolu** [comment]
The new window would be ignored directly because it was empty and on! would be called at some point so it would end up not being listed anymore. at least that's my understanding.

You should check the discussion here as well: https://github.com/spolu/dwm.vim/pull/9

Cheers

**Comment by spolu** [comment]
vim does that. it unlists empty, unchanged hidden buffers

**Comment by lmarburger** [comment]
You're right. I just tried a clean vim with only pathogen and dwm.vim loaded and the new buffer was removed. I guess I have a setting or plugin that changes that behavior. I need to figure out what it is because I'd much prefer the default.

**Comment by lmarburger** [comment]
While we're on the subject, what is the expected behavior if a new buffer is created with `C-n` then another buffer is switched to and focused with `C-h`? Should the new buffer be removed? That's what happens now I just want to confirm that's what _should_ happen.

**Comment by spolu** [comment]
I like this behavior but it's open for discussion if we can prevent it... I would love to know how it is prevented if you find your culprit. at least out of curiosity ;-)

**Comment by lmarburger** [comment]
Looks like it's `hidden`. Using a naked vim, unused buffers are cleared when `only` is called. After calling `:set hidden`, `[No Name]` buffers stick around. My only purpose for using `hidden` is so vim doesn't yell at me for hiding buffers with unsaved changes. I'd like to keep that behavior while also cleaning up empty buffers if possible.

**Pull request merged**
