### PR TITLE
Vertical resizing with Ctrl-H and Ctrl-L

### PR DESCRIPTION
**Pull request by tony**
trying to get a vertical resize working.

I switch master to `<Ctrl-T>` to free Ctrl-H and Ctrl-L for resize.  This is similar to xmonad, awesome and the late scrotwm.

### CODE REVIEW

**Comment by spolu** [comment]
That's interesting. let me checkout your branch asap tomorrow to test it. It makes total sense. I'm not still convinced by the `C-T`... but why not. 

How about a CTRL-space or CTRL-Enter? What's your thoughts on this?

**Comment by spolu** [comment]
- BTW sorry for the tutorial-like previous pull request comments, It looks like you know how to handle branches nicely since you made 2 unrelated PRs!

**Comment by tony** [comment]
@spolu:
- http://xmonad.org/manpage.html
- http://awesome.naquadah.org/doc/manpages/awesome.1.html
- https://opensource.conformal.com/cgi-bin/man-cgi?spectrwm

The above all use `Modkey-Return` or `Modkey-Ctrl-Return` to swap.

Mapping to a `Ctrl-Return` may not be a trivial task. `Ctrl-M` is a carriage return as it stands.

My $0.02: I think we should pick aesthetically pleasant default that resembles tiling WM's. While I'm not attached to `Ctrl-Enter`, `h` and `l` are used in awesome/xmonad/spectrwm to shrink/grow the master window. When opening up the plugin for the first time, it was my first itch to scratch.

Ultimately, it will expected to let user's define their own shortcuts.

On a side note, `dwm` is and all tiled wm's are awesome. If you have time, give xmonad, awesome and spectrwm a whirl to get a feel for how they handle resizing the master.

**Comment by mxmilkiib** [comment]
++mod-h/mod-l for resizing

**Comment by matze** [comment]
`<C-T>` is the default for jumping back on the tag stack and mapped by default. So this will probably lead to _a lot_ of broken Vim configurations.

**Comment by spolu** [comment]
@matze agreed

**Comment by spolu** [comment]
So how about CTRL-Space ?

**Comment by mitnk** [comment]
@spolu `C-Space` is widely used for the system-level Spotlight find on Mac OS X.

**Comment by spolu** [comment]
@mitnk indeed.
How about C-S-j / C-S-k for growing / shrinking the window?

**Comment by mitnk** [comment]
@spolu Three keys are too many keys I think.

I think we can use `ALT-<Arrow>` or `Command-<Arrow>` for resizing, they seems more natural.

Inspired by [this link](http://stackoverflow.com/questions/4368690/with-vim-how-would-one-increase-the-vertical-split-window-size/4373470#4373470).

**Comment by spolu** [comment]
Let's keep everything under the C- format since we only have basic features at the moment, no?

Since default vim is `C-<` `C->` we could use in the spirit of dwm.vim a simpler form: `C-,` and `C-.` and there fore keep the C-H for focusing. This way all keys are map the same way and in the same region of the keyboard.

**Comment by tony** [comment]
I agree with the Ctrl key. C-, and C-. adds and subtracts from master for in my configs. Ctrl-H for shrinking master is a must for me, as well as other tilers which aren't using dwm.

Regarding shortcuts, dwm purity, etc.

I think the idea bringing tiling to vim is brilliant. Do you want this plugin to be lite like dwm? I'd be happy to create a branch/fork of this project biased toward awesome, spectre, xmonad, etc. Because in order to emulate more sophisticated switching, pushing, etc, it will be significantly much more code and complexity. It wouldn't follow the spirit of dwm's liteness anymore.

What do you think? Should we work on dwm.vim in spirit of dwm and place more sophisticated stuff somewhere else?

**Comment by spolu** [comment]
I think I'd like to keep it simple. But I'm open to adding some features. 
What is featured [here](http://xmonad.org/tour.html) seems like a good feature set, no?

In that case we can maybe ~mimic the keybindings shown there with something like:

`C-J`: previous window
`C-K`: next window

`C-N`: create window
`C-C`: kill window
`C-Space`: focus window

`C-H`: shrink master
`C-L`: grow master

`C-M`: full screen / wide / normal mode

`C-,`: incr master pane window number
`C-.`: decr master pane window number

We can aim for that and take it from there? Would this work for everyone?

**Comment by tony** [comment]
I support these defaults and these features. Xmonad is baws 8-)

Further the configuration option for user to opt out of these defaults and map their own overrides. Would be happy to help. We should figure out milestones for implementing this.

T

**Comment by spolu** [comment]
What do you mean by "configuration option" ?

**Comment by tony** [comment]
It seems that this add on by default is going to remap a lot of keys. There is potential this may cause conflicts.

I suggest a configuration option to allow custom mappings to resize/shift/etc functions. The same way tiling wm's do it.

**Comment by spolu** [comment]
New bindings (or draft of new bindings) added in this commit: 9a25ff0e8c123faeb917f93641f0d80f49fee2fa

**Comment by lmarburger** [comment]
Apparently `Enter` calls `C-M` so that if you remap the later, the former is also affected.

```
+         or          *+*
CTRL-M    or          *CTRL-M* *<CR>*
<CR>      [count] lines downward, on the first non-blank
          character |linewise|.
```

**Comment by lmarburger** [comment]
What's the behavior of "increment/decrement master pane window number" bindings? Does that add/subtract the number of master windows or does it rotate all windows clockwise/counterclockwise?

**Comment by lmarburger** [comment]
Oh wow. `<C-Space>` is interpreted in vim as `<C-@>`.

On the subject of mappings, is there any reasons why all of these shouldn't be `nmap` and `silent`?

**Comment by spolu** [comment]
This has been merged in #18. closing

**Pull request closed without merging**
